language: node_js

before_install:
 - sudo apt-get install libgmp3-dev

before_script:
 - scripts/gen_keys.js

node_js:
 - "0.8"
 - "0.10"

notifications:
  email:
    - lloyd@hilaiel.com
    - bwong@mozilla.com
